"""Initial model

Revision ID: 824d587bced8
Revises: 
Create Date: 2017-02-20 17:23:56.654723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824d587bced8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('login', name=op.f('pk_user'))
    )
    op.create_index('email_index', 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_index', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
