#! /usr/bin/env python3

import os
import os.path as osp
import sys
import subprocess

import click

@click.group()
def cli():
    pass

@cli.command()
@click.argument('directory', type=click.Path(exists=False, file_okay=False))
def new(directory):    
    print('Creating new cati_manager instance in', directory)
    os.mkdir(directory)
    venv = osp.join(directory, 'venv')
    subprocess.check_call([sys.executable, '-m', 'venv', venv]) 

    env = os.environ.copy()
    env['PGDATA'] = osp.join(directory, 'postgresl')
    subprocess.check_call(['pg_ctl', 'initdb'], env=env)
    
    
if __name__ == '__main__':
    try:
        cli()
    except Exception as e:
        print('ERROR:', e, file=sys.stderr)
        sys.exit(1)
    sys.exit(0)